//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EtiquetasProduccion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Folio
    {
        public int Id { get; set; }
        public string OrderNumber { get; set; }
        public Nullable<int> Total_Pcs { get; set; }
        public Nullable<System.DateTime> Date_ { get; set; }
    }
}
